name: "Run E2E Test"

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Next Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          APP_BASE_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-ochre.vercel.app"
        with:
          build: npm run build
          start: npm run start
